# Generated by Django 5.0.1 on 2024-02-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_original_bag_order_stripe_pid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
    ]
