# Generated by Django 4.1.9 on 2024-02-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_wishlist_product_liked_productsikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='liked_productsikes',
            new_name='likes',
        ),
    ]
