# Generated by Django 4.2.11 on 2024-03-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_liked_productsikes_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.DeleteModel(
            name='add_wishlist',
        ),
    ]
